version: "3.8"

services:

  #PHP service
  app:
    build:
      dockerfile: ./docker/Dockerfile
    container_name: php
    working_dir: /var/www/The-Mini-Crossword/docker/
    volumes:
      - ../app:/var/www/The-Mini-Crossword/app
    networks:
      - app-network

  #Nginx service
  webserver:
    image: nginx:latest
    container_name: webserver
    working_dir: /var/www/The-Mini-Crossword/docker/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www/The-Mini-Crossword/app
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
